In [8]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("omarshahrukh/toyota-stock-prices-1980-2026-historical-data")

print("Path to dataset files:", path)

Path to dataset files: /Users/kaashif/.cache/kagglehub/datasets/omarshahrukh/toyota-stock-prices-1980-2026-historical-data/versions/1

In [15]:
import pandas as pd
from pathlib import Path


# Read the CSV file into a dataframe using pathlib for better path handling
csv_path = Path(path) / "Toyota_Stock_Prices_1980_2026.csv"
df = pd.read_csv(csv_path)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11508 entries, 0 to 11507
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    11508 non-null  str
 1   Close   11508 non-null  float64
 2   High    11508 non-null  float64
 3   Low     11508 non-null  float64
 4   Open    11508 non-null  float64
 5   Volume  11508 non-null  int64
dtypes: float64(4), int64(1), str(1)
memory usage: 539.6 KB

In [11]:
csv_path = Path(path) / "Toyota_Stock_Prices_1980_2026.csv"

In [12]:
csv_path

PosixPath('/Users/kaashif/.cache/kagglehub/datasets/omarshahrukh/toyota-stock-prices-1980-2026-historical-data/versions/1/Toyota_Stock_Prices_1980_2026.csv')

In [2]:
import pandas as pd

df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
df

     A    B
0  1.0  4.0
1  NaN  5.0
2  3.0  NaN

In [11]:
df.interpolate(method='linear')

     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  5.0

In [12]:
filled_data = df.interpolate(method='nearest')

In [13]:
filled_data

     A    B
0  1.0  4.0
1  1.0  5.0
2  3.0  NaN

In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Create a sample dataset
data = {
'X1': [1, 2, 3, 4, 5],
'X2': [5, 7, np.nan, 11, 13],
'Y': [10, 14, np.nan, 22, 26]
}
df = pd.DataFrame(data)

In [15]:
df

   X1    X2     Y
0   1   5.0  10.0
1   2   7.0  14.0
2   3   NaN   NaN
3   4  11.0  22.0
4   5  13.0  26.0

In [17]:
mean_x2 = df['X2'].dropna().mean()
mean_x2

np.float64(9.0)

In [18]:
df['X2'].fillna(mean_x2, inplace=True)

/var/folders/xd/4rb35j41385021wtcs07_68m0000gn/T/ipykernel_41480/2067172951.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['X2'].fillna(mean_x2, inplace=True)

0     5.0
1     7.0
2     9.0
3    11.0
4    13.0
Name: X2, dtype: float64

In [19]:
train_data = df[df['Y'].notnull()]

In [20]:
train_data

   X1    X2     Y
0   1   5.0  10.0
1   2   7.0  14.0
3   4  11.0  22.0
4   5  13.0  26.0

In [21]:
test_data = df[df['Y'].isnull()]
test_data

   X1  X2   Y
2   3 NaN NaN

In [25]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

data = {
    'X1': [1, 2, 3, 4, 5],
    'X2': [5, 7, np.nan, 11, 13],
    'Y': [10, 14, np.nan, 22, 26]
}
df = pd.DataFrame(data)

# Impute missing values in X2 with mean
mean_x2 = df['X2'].dropna().mean()
df['X2'] = df['X2'].fillna(mean_x2)  # avoid inplace on a slice

# Separate rows — use .copy() to avoid SettingWithCopyWarning
train_data = df[df['Y'].notnull()].copy()
test_data = df[df['Y'].isnull()].copy()

# Fit model
model = LinearRegression()
model.fit(train_data[['X1', 'X2']], train_data['Y'])

# Predict missing Y — now safe because test_data is a proper copy
test_data['Y'] = model.predict(test_data[['X1', 'X2']])

# Combine
df_imputed = pd.concat([train_data, test_data]).sort_index()
print(df_imputed)

   X1    X2     Y
0   1   5.0  10.0
1   2   7.0  14.0
2   3   9.0  18.0
3   4  11.0  22.0
4   5  13.0  26.0